# Generated by Django 2.1.5 on 2019-02-27 23:57

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190227_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Projetos\\DjangoProjects\\digital_marketplace\\static_cdn\\protected'), upload_to=products.models.download_media_location),
        ),
    ]
